services:
  mongoDb:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
  mongoDbAdmin:
    image: mongo-express
    restart: always
    ports:
      - '8081:8081'
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=example
      - ME_CONFIG_MONGODB_URL=mongodb://root:example@mongoDb:27017/
    depends_on:
      - mongoDb
  app:
    image: node:18.17.1-alpine
    working_dir: /app
    volumes:
      - ./app/:/app/
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - UPLOAD=upload
      - MONGO_URL=mongodb://root:example@mongoDb:27017/
    depends_on:
      - mongoDb
    command: npm run dev
