services:
  storage:
    image: redis
    volumes:
      - ./data:/data
  counter:
    build: ./counter/
    working_dir: /counter
    ports:
      - 3001:3001
    environment:
      - PORT=3001
      - REDIS_URL=redis://storage
    depends_on:
      - storage
  app:
    build: ./app
    working_dir: /app
    volumes:
      - ./app/upload:/app/upload
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - UPLOAD=upload
      - COUNTER_URL=http://counter:3001
    depends_on:
      - counter
