services:
  storage:
    image: redis
    volumes:
      - ./data:/data
  counter:
    image: node:18.17.1-alpine
    working_dir: /counter
    volumes:
      - ./counter:/counter
    ports:
      - 3001:3001
    environment:
      - PORT=3001
      - REDIS_URL=redis://storage
    depends_on:
      - storage
    command: npm run dev
  app:
    image: node:18.17.1-alpine
    working_dir: /app
    volumes:
      - ./app/:/app/
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - UPLOAD=upload
      - COUNTER_URL=http://counter:3001
    depends_on:
      - counter
    command: npm run dev
